version: '3.8'

services:
  backend:
    image: pojesh/prism_24gai15vitc-backend:1.0
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
      - ~/.cache/huggingface:/root/.cache/huggingface
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all

  frontend:
    image: pojesh/prism_24gai15vitc-frontend:1.0 
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app/frontend
    depends_on:
      - backend
